config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'questions#index'
  post "/voteup", to: "votes#voteup"
	post "/votedown", to: "votes#votedown"
  resources :questions
  resources :answers, only: [:create, :destroy]
  resources :comments

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  title      :text
#  body       :text
#  votes      :integer          default(0)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Question < ApplicationRecord
  belongs_to :user
  has_many :answers, dependent: :destroy
	has_many :votes, as: :voteable, dependent: :destroy
  has_many :comments, as: :commentable, dependent: :destroy
  
  validates :title, presence: {message: "no puede estar vacio"}
  validates :body, length: { minimum: 20 }
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, :except => [:show, :index]
    def new
        @question =Question.new
      end
      def index
          if params[:filtro]
          
            @questions = Question.joins(:user)
              .where("username like ?", "%#{params[:filtro]}%")
              .or(
                Question.joins(:user)
                  .where("title like ?", "%#{params[:filtro]}%")
              )
              .or(
                Question.joins(:user)
                  .where("body like ?", "%#{params[:filtro]}%")
              )

              
            
          else
            @questions = Question.all 
          end
      end
      def create
        @question =Question.create(questions_params)
        @question[:user_id] = current_user[:id]
        @question.save
        #redirect_to questions_path(@question)
        
      end
      def show
        @question  =Question.find(params[:id])
        @answer = Answer.new
        @comment = Comment.new
        @vote = Vote.new
      end
    
      def destroy
        question =Question.find(params[:id])
        question.destroy
      
        redirect_to questions_path
      end
    
      def edit
        @question  =Question.find(params[:id])
      end
    
      def update
        @question =Question.find(params[:id])
        if @question.update(questions_params)
          redirect_to question_path, notice: "Question reload!"
        else
          render :edit
        end
      end
        private
        def questions_params
          params.require(:question).permit(:title,:body)
        end
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_for question do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class: "form-control" %>
	</div>

	<div class="form-group">
		<%= f.label :body %>
		<%= f.text_area :body, rows: 5, class: "form-control" %>
	</div>

	<%= f.submit 'Add question', class: 'btn btn-primary' %>
<% end %>

app/views/questions/_formnew.html.erb
<div id="product-modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">
                    <%= title %>
                </h4>
            </div>

            <%= form_for @question, remote:true do |f| %>
                <div class="form-group">
                    <%= f.label :title %>
                        <%= f.text_field :title, class: "form-control" %>
                </div>

                <div class="form-group">
                    <%= f.label :body %>
                        <%= f.text_area :body, rows: 5, class: "form-control" %>
                </div>

                        <div class="modal-footer">
                            <%= f.submit 'Add question',class: "btn btn-primary btn-lg btn-block" %>
                        </div>
                        <% end %>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

app/views/questions/_row.html.erb
<div class="panel panel-default">
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-1">
                <div class="text-center">
                    <%= question.votes.length %>
                </div>
                <div class="text-center">votes</div>
            </div>
            <div class="col-sm-1">
                <div class="text-center">
                    <%= question.answers.length%>
                </div>
                <div class="text-center">answer</div>
            </div>
            <div class="col-sm-1">
                <div class="text-center">0</div>
                <div class="text-center">views</div>
            </div>
            <div class="col-sm-2"></div>
            <div class="col-sm-6">
                <%=link_to(question.title, question_path(question))%>
                    <div>posted by
                        <%= question.user.username%>
                    </div>
            </div>
        </div>
    </div>
</div>

app/views/questions/create.js.erb
<% if @question.errors.empty? %>
  // add the row to the table, show alert and hide modal
  $('.body').append(' <%= j render "row", question: @question %>');
  $('.flash').html("The question has been added successfully");
  $('.alert-success').show();
  $('#product-modal').modal('hide');
<% else %>
  // show first error
  alert('<%= @question.errors.full_messages[0] %>');
<% end %>

app/views/questions/edit.html.erb
<%= render 'form',  question: @question%>

app/views/questions/index.html.erb
<div>
<%if signed_in?%>
 <%= link_to "Ask a question", new_question_path, remote: true, class: "btn btn-info pull-right" %>

<%else%>
<a data-toggle="modal" href="#login" class="btn btn-info pull-right" role="button">Ask a question</a>

 <%end%>
<div class="panel panel-default" style="margin-top:50px">
    <div class="panel-heading">
        <h3>Questions</h3>
    </div>
    <div class="panel-body  body">
            <% @questions.each do |question|%>
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                        <div class="col-sm-1"></div>
                            <div class="col-sm-1"><div class="text-center"><%= question.votes.length %></div><div class="text-center">votes</div></div>
                            <div class="col-sm-1"><div class="text-center"><%= question.answers.length%></div><div class="text-center">answer</div></div>
                            <div class="col-sm-1"><div class="text-center">0</div><div class="text-center">views</div></div>
                            <div class="col-sm-2"></div>
                            <div class="col-sm-6"><%=link_to(question.title, question_path(question))%><div>posted by <%= question.user.username%></div></div>
                        </div>
                    </div>
                </div>
                <% end%>
                
    </div>
</div>
</div>

app/views/questions/new.html.erb
<%= render 'form',  question: @question%>

app/views/questions/new.js.erb
$('<%= j render "formnew", title: "New question" %>').on('hidden.bs.modal', function (e) {
  $(this).remove();
  $('.modal-backdrop').remove();
}).modal();

app/views/questions/show.html - copia.erb
<div class="panel-group">
  <div class="row">

    <!-- Aqui va el input de votos -->
    <div class="col-sm-1 text-center">
      <form action="#">
        <button class="btn" type="submit">
          <i class="glyphicon glyphicon glyphicon-menu-up"></i>
        </button>
        <label class="h2" style="display: block;">0</label>

        <button class="btn" type="submit">
          <i class="glyphicon glyphicon glyphicon-menu-down"></i>
        </button>
      </form>
    </div>

    <!-- Aqui va  el panel de pregunta-->
    <div class="col-sm-7">
      <div class="panel panel-default ">
        <div class="panel-heading">
          <h3>
            <%= @question.title %>
          </h3>
        </div>
        <div class="panel-body h-body">
          <%=@question.body%>
        </div>
      </div>
    </div>
    <!-- Aqui va el panel de comentarios de la pregunta -->
    <div class="col-sm-4 ">
      <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">Comments</div>
        <!-- List group -->
        <ul class="list-group  h-comment">

          <%@question.comments.each do |comment|%>
            <li class="list-group-item">
              <a href="#"><%= comment.user.username%></a> said:
              <%= comment.body%>
            </li>
            <%end%>
        </ul>
      </div>
      <br>

      <!-- Aqui va el input de comentarios de pregunta -->
      <%= form_for @comment, :url => comments_path do |f| %>
        <%= f.hidden_field :commentable_id, value: @question.id %>
          <%= f.hidden_field :commentable_type, value: "Question" %>
            <%= f.hidden_field :user_id, value: current_user[:id] if !current_user.nil? %>
              <div class="form-group">
                <%= f.text_area :body, rows: 5, class: "form-control" %>
              </div>
              <%= f.submit 'Send', class: 'btn btn-default pull-right' %>
                <% end %>
    </div>

  </div>

</div>

<hr>
<!-- Aqui empiezan las respuestas -->
<h2><%= @question.answers.length%> Answers</h2>
</br>
</br>
<%=@question.answers.each do |answer|%>

  <div class="panel-group">
    <div class="row">
      <div class="col-sm-1 text-center">
        <form action="#">
          <button class="btn" type="submit">
            <i class="glyphicon glyphicon glyphicon-menu-up"></i>
          </button>
          <label class="h2" style="display: block;">0</label>

          <button class="btn" type="submit">
            <i class="glyphicon glyphicon glyphicon-menu-down"></i>
          </button>
        </form>
      </div>

      <div class="col-sm-7">
        <div class="panel panel-default ">
          <div class="panel-body h-body">
            <%=answer.body%>
          </div>
        </div>
      </div>

      <div class="col-sm-4 ">
        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading">Comments</div>
          <!-- List group -->
          <ul class="list-group  h-comment">
            <%answer.comments.each do |comment|%>
              <li class="list-group-item">
              <a href="#"><%= comment.user.username%></a> said:
              <%= comment.body%>
            </li>
              <%end%>
          </ul>

        </div>
        <br>

        <!-- Aqui va el input de comentarios de pregunta -->
        <%= form_for @comment, :url => comments_path do |f| %>
          <%= f.hidden_field :commentable_id, value: answer.id %>
            <%= f.hidden_field :commentable_type, value: "Answer" %>
              <%= f.hidden_field :user_id, value: current_user[:id] if !current_user.nil? %>
                <div class="form-group">
                  <%= f.text_area :body, rows: 5, class: "form-control" %>
                </div>
                <%= f.submit 'Send', class: 'btn btn-default pull-right' %>
                  <% end %>
      </div>

    </div>

  </div>
  <hr>
  <%end%>
  
  <hr>

    <%= form_for @answer, :url => answers_path do |f| %>
      <%= f.hidden_field :question_id, value: @question[:id] %>
        <%= f.hidden_field :user_id, value: current_user[:id] if !current_user.nil? %>
          <div class="form-group">
            <%= f.text_area :body, rows: 5, class: "form-control" %>
          </div>
          <%= f.submit 'Enviar Respuesta', class: 'btn btn-primary' %>
     <% end %>

app/views/questions/show.html.erb
<div class="panel-group">
  <div class="row">

    <!-- Aqui va el input de votos -->
    <div class="col-sm-1 text-center">
      <div class="container-votes">
        <div>
          <%= form_for @vote, url: voteup_path do |f| %>
            <%= f.hidden_field :voteable_id, value: @question[:id] %>
            <%= f.hidden_field :user_id, value: current_user[:id] if !current_user.nil? %>
            <%= f.hidden_field :voteable_type, value: "Question" %>
              <%= f.button :submit , class: "btn" do %>
              <i class='glyphicon glyphicon glyphicon-menu-up'></i>
              <% end %>
          <% end %>
        </div>

        <div>
          <h3 class="vote has-vote">
            <%= @question.votes.length %>
          </h3>

        </div>

        <div>
          <%= form_for @vote, url: votedown_path do |f| %>
            <%= f.hidden_field :voteable_id, value: @question[:id] %>
            <%= f.hidden_field :user_id, value: current_user[:id] if !current_user.nil? %>
            <%= f.hidden_field :voteable_type, value: "Question" %>
              <%= f.button :submit , class: "btn" do %>
              <i class='glyphicon glyphicon glyphicon-menu-down'></i>
              <% end %>
          <% end %>
        </div>

      </div>
    </div>
    <!-- Aqui va  el panel de pregunta-->
    <div class="col-sm-7">
      <div class="panel panel-default ">
        <div class="panel-heading">
          <h3>
            <%= @question.title %>
          </h3>
        </div>
        <div class="panel-body h-body">
          <%=markdown(@question.body)%>
        </div>
      </div>
      <% if !current_user.nil? %>
        <%= link_to 'Delete', @question, method: :delete, data: {confirm: 'Are you sure you want to eliminate the answer? Comments and votes associated with it are not displayed.'}, class: 'btn btn-primary' if @question[:user_id] == current_user[:id] %>
        <%= link_to 'Edit', edit_question_path(@question), class: 'btn btn-primary' if @question[:user_id] == current_user[:id]%>
      <% end %>
    </div>

    <!-- Aqui va el panel de comentarios de la pregunta -->
    <div class="col-sm-4 ">
      <div class="panel panel-default">
        <!-- Default panel contents -->
        <div class="panel-heading">Comments</div>
        <!-- List group -->
        <ul class="list-group  h-comment">

          <%@question.comments.each do |comment|%>
            <li class="list-group-item">
              <a href="#">
                <%= comment.user.username%>
              </a>:
              <%= comment.body%>
            </li>
            <%end%>
        </ul>
      </div>
      <br>

      <!-- Aqui va el input de comentarios de pregunta -->
      <%= form_for @comment, :url => comments_path do |f| %>
        <%= f.hidden_field :commentable_id, value: @question.id %>
        <%= f.hidden_field :commentable_type, value: "Question" %>
        <%= f.hidden_field :user_id, value: current_user[:id] if !current_user.nil? %>
        <div class="form-group">
        <%= f.text_area :body, rows: 5, class: "form-control" %>
        </div>
        <%= f.submit 'Send', class: 'btn btn-default pull-right' %>
      <% end %>
    </div>

  </div>

</div>

<hr>
<!-- Aqui empiezan las respuestas -->
<h2>
  <%= @question.answers.length%> Answers</h2>
</br>
</br>
<%@question.answers.each do |answer|%>

  <div class="panel-group">
    <div class="row">
      <div class="col-sm-1 text-center">
        <div class="container-votes">
          <div>
            <%= form_for @vote, url: voteup_path do |f| %>
              <%= f.hidden_field :voteable_id, value: answer[:id] %>
              <%= f.hidden_field :user_id, value: current_user[:id] if !current_user.nil? %>
              <%= f.hidden_field :voteable_type, value: "Answer" %>
                <%= f.button :submit , class: "btn" do %>
                <i class='glyphicon glyphicon glyphicon-menu-up'></i>
                <% end %>
            <% end %>
          </div>

          <div>
            <h3 class="vote has-vote">
              <%= answer.votes.length %>
            </h3>

          </div>

          <div>
            <%= form_for @vote, url: votedown_path do |f| %>
              <%= f.hidden_field :voteable_id, value: answer[:id] %>
              <%= f.hidden_field :user_id, value: current_user[:id] if !current_user.nil? %>
              <%= f.hidden_field :voteable_type, value: "Question" %>
                <%= f.button :submit , class: "btn" do %>
                <i class='glyphicon glyphicon glyphicon-menu-down'></i>
                <% end %>
            <% end %>
          </div>

        </div>
      </div>

      <div class="col-sm-7">
        <div class="panel panel-default ">
          <div class="panel-body h-body">
            <%=markdown(answer.body)%>
          </div>
        </div>
        <% if !current_user.nil? %>
          <%= link_to 'Delete', answer, method: :delete, data: {confirm: '¿Esta seguro de eliminar la respuesta?. Los comentarios y votos asociados a ella no podrán visualizarse'}, class: 'btn btn-primary' if answer[:user_id] == current_user[:id] %>
        <% end %>
      </div>

      <div class="col-sm-4 ">
        <div class="panel panel-default">
          <!-- Default panel contents -->
          <div class="panel-heading">Comments</div>
          <!-- List group -->
          <ul class="list-group  h-comment">
            <%answer.comments.each do |comment|%>
              <li class="list-group-item">
                <a href="#">
                  <%= comment.user.username%>
                </a>:
                <%= comment.body%>
              </li>
            <%end%>
          </ul>

        </div>
        <br>

        <!-- Aqui va el input de comentarios de respuesta -->
        <%= form_for @comment, :url => comments_path do |f| %>
          <%= f.hidden_field :commentable_id, value: answer.id %>
          <%= f.hidden_field :commentable_type, value: "Answer" %>
          <%= f.hidden_field :user_id, value: current_user[:id] if !current_user.nil? %>
          <div class="form-group">
          <%= f.text_area :body, rows: 5, class: "form-control" %>
          </div>
          <%= f.submit 'Send', class: 'btn btn-default pull-right' %>
        <% end %>
      </div>

    </div>

  </div>
  <hr>
  <%end%>


    <%= form_for @answer, :url => answers_path do |f| %>
      <%= f.hidden_field :question_id, value: @question[:id] %>
      <%= f.hidden_field :user_id, value: current_user[:id] if !current_user.nil? %>
      <div class="form-group">
      <%= f.text_area :body, rows: 5, class: "form-control" %>
      </div>
      <%= f.submit 'Send answer', class: 'btn btn-primary' %>
    <% end %>