config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root 'questions#index'
  post "/voteup", to: "votes#voteup"
	post "/votedown", to: "votes#votedown"
  resources :questions
  resources :answers, only: [:create, :destroy]
  resources :comments

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %>">
    <a href="#" data-dismiss="alert" class="close">×</a>
    <ul>
      <li>
        <%= value %>
      </li>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Stack</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <style>
          .text-center {
            text-align: center;
          }

          .h-body {
            min-height: 300px;
          }

          .h-comment {
            max-height: 300px;
            overflow-y: auto;
          }
        </style>
</head>

<body>


  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="/">Flow Overstack</a>
      </div>
      <ul class="nav navbar-nav">

        <li>
          <a href="#">Questions</a>
        </li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li>
            <a href="#">
              <%=current_user[:username]%>
            </a>
          </li>
          <!--<li><a href="users/sign_out" data-method="delete"><span class="glyphicon glyphicon-log-in"></span> Sign out</a></li> -->
          <li>
            <%= link_to("<span class='glyphicon glyphicon-log-in'></span> Exit".html_safe, destroy_user_session_path , :method => :delete)%>
          </li>
          <%else%>
            <li>
              <a data-toggle="modal" href="#singup">
                <span class="glyphicon glyphicon-user"></span> Sign Up</a>

            </li>
            <li>
              <a data-toggle="modal" href="#login">
                <span class="glyphicon glyphicon-log-in"></span> Login</a>
            </li>
            <%end%>
      </ul>
      <form class="navbar-form navbar-right" action="/">
        <input type="text" href="/question/" name="filtro" class="form-control" placeholder="Search">
      </form>
    </div>
  </nav>

  <!-- Modal -->
  <div id="singup" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title text-center h2">Sing up</h4>
        </div>
        <div class="modal-body ">
          <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
            <%= devise_error_messages! %>
              <div class="field">
                <%= f.label :email %>
                  <br />
                  <%= f.email_field :email, autofocus: true, autocomplete: "email",:class =>"form-control" %>
              </div>

              <div class="field">
                <%= f.label :username %>
                  <br />
                  <%= f.text_field :username, autofocus: true, :class =>"form-control"%>
              </div>

              <div class="field">
                <%= f.label :password %>
                  <% if @minimum_password_length %>
                    <em>(
                      <%= @minimum_password_length %> characters minimum)</em>
                    <% end %>
                      <br />
                      <%= f.password_field :password, autocomplete: "off",:class =>"form-control" %>
              </div>

              <div class="field">
                <%= f.label :password_confirmation %>
                  <br />
                  <%= f.password_field :password_confirmation, autocomplete: "off", :class =>"form-control"%>
              </div>

              <div class="actions">
                <br>
                <%= f.submit "Sign up", :class =>"form-control btn btn-info" %>
              </div>
              <% end %>

                <%= render "devise/shared/links" %>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>

  <div class="modal custom fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">
            &times;
          </button>
          <h2 class="text-center h2">Login</h2>
        </div>
        <div class="modal-body">
          <%= form_for(:user, :url => session_path(:user)) do |f| %>
            <div class="email-container">
              <%= f.text_field :email, :class =>"form-control",placeholder: "Email", value:"" %>
            </div>
            <br>
            <div class="password-container">
              <%= f.password_field :password,:label =>"Password", :class =>"form-control", placeholder:"Password", value:""%>
            </div>
            <br>
            <%= f.submit 'Login', :class =>"form-control btn btn-info" %>
              <%= f.check_box :remember_me, label: "Remember me", value: "true" %>
                <%= f.label :remember_me %>
                  <% end %>
        </div>
      </div>
    </div>
  </div>



  <div class="container">

    <div class="alert alert-success alert-dismissible" style="display: none;">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <div class="flash">
      </div>
    </div>
    <%= render 'layouts/messages' %>

      <%= yield %>
  </div>
</body>

</html>